Tasks 3.2-3.6
js-tasks-ru/vue-20220616_martech pull request #4
Opened 2022-06-26 12:01 UTC by wrkmartech

2022-06-26 12:02 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-28 15:17 UTC, ShGKme requested changes
В `02-components/03-MeetupCover` требуется заменить метод на вычисляемое свойство. 

Все остальные задачи приняты 👍🏻

2022-06-28 15:17 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +        return Object.values(dateParts).join('-');
По спецификации атрибута datetime в нём должна быть дата по UTC, а методы getX в Date вычисляют дату в локальном часовом поясе, что иногда может давать некорректную дату. Дату по ISO можно получить из метода `toISOString()` у даты.

Повторяющиеся места можно также брать готовые из материалов с вебинаров:
https://github.com/js-tasks-ru/vue3-course-materials/blob/master/02-components/02-page-meetups/components/MeetupCard.js#L26-L38

2022-06-28 15:17 UTC, ShGKme commented on 02-components/05-MeetupAgenda/MeetupAgendaItem.js
> +  },
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства обычно называют, как свойства, а не как функции (не с глагола, без get).

2022-06-28 20:31 UTC, ShGKme reviewed
Все исправления приняты, но добавлены новые задачи

2022-06-30 14:52 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-06-30 14:53 UTC, merged