Tasks 5.1-5.2
js-tasks-ru/vue-20220616_martech pull request #5
Opened 2022-07-01 13:42 UTC by wrkmartech

2022-07-01 13:42 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-07-01 19:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-01 19:50 UTC, wrkmartech commented
Возник небольшой вопрос по тестированию задачи "UiDropdown1": если в компоненте UiDropdown сделать modelValue в props как required: true, то появляется сообщение "[Vue warn]: Missing required prop: "modelValue"...". Тест не понимает, что v-model на компоненте уже содержит "modelValue" или причина варнинга какая-то иная?

2022-07-01 20:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-02 12:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-03 13:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-03 22:47 UTC, ShGKme commented
> Возник небольшой вопрос по тестированию задачи "UiDropdown1": если в компоненте UiDropdown сделать modelValue в props как required: true, то появляется сообщение "[Vue warn]: Missing required prop: "modelValue"...". Тест не понимает, что v-model на компоненте уже содержит "modelValue" или причина варнинга какая-то иная?

Некоторые тесты не передают `modelValue` (не устанавливают никакой `v-model`), проверяя только, как рендерится кнопка со списком вариантов. Чтобы не было `warn`, можно убрать требование обязательности `modelValue` с `required: true`. Компонент корректно работает и без установленного `modelValue` (корректно выводит список вариантов).

2022-07-03 22:50 UTC, ShGKme requested changes
В целом всё отлично, но предлагаю закрепить некоторые стилистические места:

1. В `01-UiFormGroup` и `03-UiDropdown1` - использовать привязку классов объектом при указании динамических классов по условию.
2. В `02-TheToaster` и `03-UiDropdown1` - убрать лишний `<template>`,
3. В `02-TheToaster` - убрать передающийся по кругу `toastId`.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +    },
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - булево значение, которое обозначает, что класс требуется добавить.

[https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings](https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings)

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +    },
На мой взгляд удобнее привязывать класс уже в шаблоне, а не вычислять его в вычисляемом свойстве. Так в шаблоне, в вёрстке сразу будет видно, какой класс может быть на этом элементе и когда. Конечно, исключая ситуации, когда классы или стили требуют сложных объёмных вычислений.

Если здесь использовать вместо тернарника объект, то и его использование в шаблоне будет удобнее.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    </template>
Элемент `<template>` в шаблоне нужен, когда требуется для директив `v-if` или `v-for` обернуть несколько узлов сразу.

Если узел один, то директиву можно использовать непосредственно на нём без лишних обёрток.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +};
С событием незачем отдавать `toastId`, который этому компоненту в целом не нужен. Его родитель итак знает, у какого тоста порождается событие `closeToast`. Он знает этот `toastId`, который сейчас получается вместе с событием, потому что он сам же ему его отдаёт. Сейчас `toastId` просто получается от родителя и отправляется ему же обратно, передаваясь по кругу.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      </ui-toast>
Здесь `TheToaster` передаёт в `UiToast` ID через `:toastId="toast.toastId"`, а потом его же ловит и использует в `@closeToast="removeToast($event)"`.

 Вместо отправки ID по кругу можно явно передать его сразу: `@closeToast="removeToast(toast.toastId)"`.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Сейчас в качестве идентификатора используется просто символ. Возможно, такой идентификатор не удобнее, чем использовать сам тост, так как `Symbol` всё равно не сериализуется в строку. Например, можно создавать объект и дальше работать с ним:

```javascript
appendToast(type, icon, text, timeout = 5000, closeButton = false) {
  const toast = { type, icon, text, toastId: toastId, intervalId, closeButton }
  let intervalId = setTimeout(this.removeToast, timeout, toast);
  this.toasts.push(toast);
},
removeToast(toast) {
  let toastIndex = this.toasts.indexOf(toast);
  clearTimeout(this.toasts[toastIndex].intervalId); // only for @closeToast
  this.toasts.splice(toastIndex, 1);
},
```

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    >
Аналогично с классом - лучше использовать объект с привязкой классов по условиям, чем собирать строку с тернарным оператором.

2022-07-03 22:50 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      </template>
Аналогично, лишний `<template>`.

2022-07-03 22:50 UTC, ShGKme commented on 05-vue-router/01-AuthPages/router/index.js
>  });
Предпочтительнее использовать динамический импорт для [code splitting-а](https://developer.mozilla.org/en-US/docs/Glossary/Code_splitting).

2022-07-03 22:50 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +      this.$router.push(redirectTo);
`this.$route.query` всегда есть. В случае отсутствия query параметров, там будет пустой объект. Можно не делать проверки с `?.`.

2022-07-03 22:50 UTC, ShGKme commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +
Аналогично, у маршрута всегда есть объект `meta`, даже если meta-свойств нет. Проверка с ?. не требуется.

2022-07-04 11:01 UTC, wrkmartech commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
`    <ui-toast
      v-for="(toast, index) in toasts"
      :key="index"
      :type="toast.type"
      :icon="toast.icon"
      :close-button="toast.closeButton"
      @closeToast="removeToast(toast)"
    >
      {{ toast.text }}
    </ui-toast>`

А какие данные в таком случае правильнее  использовать для `:key` в `v-for`? Индекс массива `index` или вообще оставить без `:key`, полагаясь на механизм Vue по умолчанию, т.к. `index` может меняться при добавлении/удалении элементов массива `toasts`.

2022-07-04 11:10 UTC, wrkmartech commented on 05-vue-router/01-AuthPages/router/index.js
>  });
В такой ситуации, наверное, стоит для главной страницы, как наиболее посещаемой пости всегда, использовать стандартную загрузку, а для всех остальных уже "Lazy Loading Routes"?

2022-07-04 15:46 UTC, ShGKme commented on 05-vue-router/01-AuthPages/router/index.js
>  });
Часто главная совсем не наиболее посещаемая. Но да, здесь можно экспериментировать, выделяя разные страницы в чанк или основной бандл.

2022-07-05 08:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-07-05 11:39 UTC, merged